/* Self-checks per lecture. c = index of the correct answer. */
"use strict";
window.QUIZZES = {
  "1": [
    { q: "When is it legitimate to replace a mechanical or acoustic part by a lumped element?", a: ["Whenever the part is made of a homogeneous material", "When the part is much smaller than the wavelength (rule of thumb: below λ/10)", "Always — the analogy is exact", "Only below 100 Hz"], c: 1, why: "Lumped means “the whole thing moves as one”. That is only true when a wave cannot vary across it, i.e. the part is small compared with λ. Homogeneity and idealisation are extra assumptions, but the size limit is the one that bites first." },
    { q: "In the <b>impedance</b> analogy a mechanical mass becomes…", a: ["a capacitor", "an inductor", "a resistor", "a transformer"], c: 1, why: "Impedance analogy: force ↔ voltage, velocity ↔ current. A mass obeys <span class='m'>f = j\\omega M u</span>, which has the same shape as <span class='m'>v = j\\omega L i</span>. In the <b>mobility</b> analogy the roles swap and the mass becomes a capacitor to ground." },
    { q: "Which pair are the power-conjugate variables of the acoustic domain?", a: ["pressure p and particle velocity u", "force f and volume velocity U", "pressure p and volume velocity U", "sound pressure level and frequency"], c: 2, why: "Their product must be a power: <span class='m'>p\\,U</span> has units Pa·m³/s = W. Pressure times particle velocity is an intensity (W/m²), not a power." },
    { q: "Differentiating in time (d/dt) becomes what in the jω method?", a: ["division by jω", "multiplication by jω", "multiplication by −1", "a 45° phase shift"], c: 1, why: "For a signal <span class='m'>e^{j\\omega t}</span>, the derivative is <span class='m'>j\\omega e^{j\\omega t}</span>: a factor jω, i.e. +90° of phase and a slope of +6 dB per octave. Integration is the reverse." },
  ],
  "2": [
    { q: "A mass on a spring with a damper is driven by a <b>force</b>. What happens to the velocity at resonance?", a: ["It drops to a minimum — the mass and spring block the motion", "It peaks — mass and spring cancel and only the damper limits it", "It is unchanged; resonance only affects phase", "It becomes infinite for any damping"], c: 1, why: "Series impedance <span class='m'>Z_M = j\\omega M + 1/(j\\omega C) + R</span>. At <span class='m'>\\omega_0</span> the two reactive terms cancel, so <span class='m'>u = f/R_M</span> — the largest it ever gets. Drive with a velocity source instead and the <i>force</i> shows a dip at the same frequency." },
    { q: "How do you convert an impedance-analogy circuit into its mobility-analogy dual?", a: ["Swap every L for a C and keep the topology", "Turn every mesh into a node, add a ground node, and replace each element with its dual", "Reverse the direction of every source", "You cannot — they describe different physics"], c: 1, why: "Duality is a topological transform: series becomes parallel, mesh equations become node equations, and each element is replaced by its dual (mass L → C, compliance C → L, damper R → 1/R). The physics is identical." },
    { q: "In the mechanical sketch, why must a mass always be drawn against a fixed reference?", a: ["Because Newton's law measures acceleration relative to an inertial frame, so one terminal of a mass is always ground", "Because masses are heavy", "Because springs need two ends", "It is only a drawing convention with no physical reason"], c: 0, why: "A spring or damper responds to the <i>relative</i> motion of its two ends. A mass responds to its absolute acceleration. In the mobility analogy that is why the mass-capacitor always hangs to ground." },
    { q: "A Thévenin force source with output impedance <span class='m'>Z_0</span> is equivalent to a Norton velocity source of…", a: ["<span class='m'>u_{No} = f_{Th} \\cdot Z_0</span>", "<span class='m'>u_{No} = f_{Th} / Z_0</span>", "<span class='m'>u_{No} = f_{Th}</span>", "there is no equivalent"], c: 1, why: "Same as electrical Thévenin ↔ Norton: <span class='m'>f_{Th} = Z_0 u_{No}</span>, so the Norton velocity is the short-circuit velocity <span class='m'>f_{Th}/Z_0</span>." },
  ],
  "3": [
    { q: "A short <b>open</b> tube of air behaves, at low frequency, like…", a: ["a compliance (capacitor)", "a resistance", "an acoustic mass (inductor), <span class='m'>M_A = \\rho l^*/S</span>", "a transformer"], c: 2, why: "From <span class='m'>Z = j(\\rho c/S)\\tan(kl)</span> with <span class='m'>\\tan(kl)\\approx kl</span> you get <span class='m'>j\\omega\\rho l/S</span>: the plug of air just sloshes as one lump — inertia, no springiness." },
    { q: "A <b>closed</b> volume V behaves, at low frequency, like…", a: ["an acoustic mass", "a compliance <span class='m'>C_A = V/(\\rho c^2)</span> — always drawn to ground", "a resistance", "an open circuit"], c: 1, why: "From <span class='m'>-j(\\rho c/S)\\cot(kl)</span> with <span class='m'>\\cot(kl)\\approx 1/kl</span> you get <span class='m'>1/(j\\omega C_A)</span>. It pushes back against still air (zero pressure), so one terminal is always the reference pressure — ground." },
    { q: "Why does the Helmholtz frequency <span class='m'>f_0 = \\frac{c}{2\\pi}\\sqrt{S/(l^* V)}</span> not contain the air density?", a: ["Because air is very light", "Because ρ appears in both <span class='m'>M_A</span> and <span class='m'>C_A</span> and cancels in <span class='m'>1/\\sqrt{M_A C_A}</span>", "It does contain ρ; the formula is approximate", "Because the derivation assumes vacuum"], c: 1, why: "<span class='m'>M_A = \\rho l^*/S</span> and <span class='m'>C_A = V/(\\rho c^2)</span>: the product is <span class='m'>l^* V/(S c^2)</span>, ρ-free. Only geometry and the speed of sound set the pitch of a bottle." },
    { q: "What does the radiation impedance of a baffled piston look like at low ka?", a: ["A pure resistance ρc/S", "Mostly a mass: the piston drags a lump of air along", "Zero — no radiation at all", "A capacitor"], c: 1, why: "Below ka ≈ 1 the imaginary part dominates and grows like ω: mass loading <span class='m'>M_{A1} = 8\\rho/(3\\pi^2 a)</span>. Only above ka ≈ 1 does the real part flatten to <span class='m'>\\rho c/S</span> and the piston radiate efficiently." },
    { q: "Where does the lumped tube/box model stop being trustworthy?", a: ["Above about λ/10 of the largest dimension", "Above 1 kHz always", "It never fails for air", "Only when the tube is closed"], c: 0, why: "Once the object is a sizeable fraction of a wavelength, pressure and flow vary along it. The exact <span class='m'>\\tan</span>/<span class='m'>\\cot</span> curves peel away from the straight lumped lines and, at λ/4, the real tube has a resonance the lumped element cannot show." },
  ],
  "4": [
    { q: "A voice coil couples the electrical and mechanical domains through…", a: ["one controlled source, <span class='m'>f = Bl\\,i</span>", "two controlled sources, <span class='m'>f = Bl\\,i</span> and <span class='m'>v = Bl\\,u</span>, both with the same constant", "a resistor of value Bl", "a capacitor of value Bl"], c: 1, why: "Transduction is bidirectional: the Lorentz force turns current into force, and Faraday induction turns velocity into voltage — same wire, same instant, same constant Bl. Draw both or the model is wrong (no back-EMF, no electrical damping)." },
    { q: "Seen from the electrical terminals, a mechanical <b>series</b> resonance of a moving-coil driver appears as…", a: ["an impedance minimum", "an impedance maximum — <span class='m'>Z_E = R_e + (Bl)^2/Z_M</span> inverts it", "nothing; the terminals only see R<sub>e</sub>", "a phase shift of 180° only"], c: 1, why: "The voice coil is a gyrator: mechanical impedance is reflected <i>inverted</i>. At <span class='m'>f_s</span> the cone moves most, the back-EMF is largest, the current smallest — the classic impedance peak, height <span class='m'>R_e + (Bl)^2/R_{ms}</span>." },
    { q: "A diaphragm of area S reflects an acoustic load <span class='m'>Z_A</span> into the mechanical domain as…", a: ["<span class='m'>Z_A / S</span>", "<span class='m'>S\\,Z_A</span>", "<span class='m'>S^2 Z_A</span>", "<span class='m'>1/(S^2 Z_A)</span>"], c: 2, why: "<span class='m'>f = S p</span> and <span class='m'>U = S u</span> give <span class='m'>f/u = S^2 (p/U)</span>. A diaphragm is a transformer (like-with-like coupling), so it scales; the voice coil is a gyrator, so it inverts." },
    { q: "Which total resistance sets a dynamic microphone's sensitivity <span class='m'>M \\approx Bl S_D / R_{MT}</span>?", a: ["only the suspension damping <span class='m'>R_{MS}</span>", "<span class='m'>R_{MS} + S_D^2 R_{AF} + (Bl)^2/(R_E+R_L)</span>", "only the felt <span class='m'>R_{AF}</span>", "the coil resistance <span class='m'>R_E</span>"], c: 1, why: "All three damping paths add in the one series loop: the suspension, the felt reflected through <span class='m'>S_D^2</span>, and the electrical load reflected through <span class='m'>(Bl)^2</span>. With a 47 kΩ load the last term is negligible and the felt dominates — it is the designer's knob." },
    { q: "Which controlled source realises “output current set by an input voltage”?", a: ["E (VCVS)", "F (CCCS)", "G (VCCS)", "H (CCVS)"], c: 2, why: "Across → through is a G source. In the mobility analogy <span class='m'>U = S u</span> is exactly that: velocity is a node voltage, volume velocity is a current." },
  ],
  "5": [
    { q: "Exposing the back of a diaphragm to the sound field turns the microphone into a…", a: ["pressure microphone with more sensitivity", "gradient microphone: it responds to dp/dx, giving a cos θ pattern and a response that rises with frequency", "condenser microphone", "microphone that no longer works"], c: 1, why: "<span class='m'>p_D = p_F - p_B = jk\\,\\Delta l\\,p\\cos\\theta</span> for a plane wave: proportional to frequency (k = ω/c) and to cos θ — a figure-8." },
    { q: "Why is a ribbon microphone inherently weak at low frequencies far from the source?", a: ["Because ribbons are thin", "Because the gradient adds a factor jω, so below resonance the response falls at 12 dB/oct (mass control is needed for a flat band)", "Because the magnet saturates", "It is not — ribbons are flat to 20 Hz"], c: 1, why: "The gradient contributes jω and the compliance-controlled diaphragm another jω below <span class='m'>f_0</span>: <span class='m'>(j\\omega)^2</span>, 12 dB/oct. Only the proximity effect (kr ≪ 1) puts the bass back." },
    { q: "In the cardioid family <span class='m'>R(\\theta) = (1 + B\\cos\\theta)/(1+B)</span>, a pure figure-8 is…", a: ["B = 0", "B = 1", "B = √3", "B → ∞"], c: 3, why: "B is the gradient share. B = 0 is omni (pure pressure), B = 1 cardioid (first rear null), √3 supercardioid, 3 hypercardioid, and as B → ∞ only the cos θ term survives: bidirectional." },
    { q: "Why is a condenser microphone's response <b>flat below</b> its resonance?", a: ["Because the polarization voltage is constant", "Because the transduction law carries a 1/jω that cancels the compliance's 1/jω: the output follows displacement, and displacement is flat where the spring rules", "Because the diaphragm has no mass", "Because the back plate has holes"], c: 1, why: "<span class='m'>e_{oc} = \\frac{E}{j\\omega x_0} u_D</span> — the output is proportional to displacement x, not velocity. Below <span class='m'>f_0</span> the spring rules, displacement per pascal is constant (<span class='m'>M = E S_D C_{MT}/x_0</span>), so the sensitivity is flat: compliance control." },
    { q: "Lab C recipe: how do you read <span class='m'>f_s</span> and Q off a measured condenser sensitivity curve?", a: ["Peak frequency and peak height in dB", "The frequency where the phase has dropped 90° from its mid-band value; Q is the linear sensitivity ratio at that frequency vs. the flat band", "The −3 dB point and the slope", "You cannot without a laser vibrometer"], c: 1, why: "At resonance the phase is −90° regardless of damping, so the phase locates <span class='m'>f_s</span> even when Q < 1 and there is no visible bump. Then <span class='m'>Q = e(f_s)/e(f \\ll f_s)</span> — which can be below 1, i.e. negative dB." },
  ],
  "6": [
    { q: "A free-field microphone differs from a pressure microphone in that…", a: ["it has a bigger diaphragm", "its own response is shaped to cancel the pressure build-up its body causes at high frequency, so it reports the field as it was before the microphone arrived", "it needs no polarization voltage", "it only works outdoors"], c: 1, why: "Scattering raises the pressure on the diaphragm (up to about +10 dB on axis near kR ≈ 3). A free-field capsule is over-damped by the same amount; a pressure capsule is flat to the pressure actually on it and is used flush-mounted or in couplers." },
    { q: "In the plane-reflection model <span class='m'>T = 1 + Z_{ar}/(\\rho c/S)</span>, what is the high-frequency limit and why?", a: ["T → 1, the wave passes around the capsule", "T → 2 (+6 dB): Z_ar → ρc/S, the stiff diaphragm reflects the wave and the pressure doubles as at a rigid wall", "T → ∞", "T → 0"], c: 1, why: "With an infinitely stiff diaphragm the reflected volume velocity equals the incident one and drives the radiation impedance. Once ka ≫ 1 that impedance is the resistance ρc/S, giving T = 2. The real curve overshoots to +10 dB because the edges diffract — the model is only valid up to the first peak." },
    { q: "Problems 6: the diaphragm mass is uncertain by 10 %. Its contribution to the uncertainty of the flat-band sensitivity M is…", a: ["10 % of M", "about 5 % of M", "zero — M = E·S_D·C_MT/x₀ does not contain M_MD, so the sensitivity coefficient ∂M/∂M_MD is 0", "impossible to say without a measurement"], c: 2, why: "Below resonance the capsule is compliance-controlled. Only C_MD (through C_MT) enters: ∂M/∂C_MD = 2370 (V/Pa)/(m/N), so 10 % of C_MD gives u(M) = 0.948 mV/Pa. Mass and damping matter at and above resonance instead." },
    { q: "How does primary (reciprocity) calibration get absolute sensitivities without a reference microphone?", a: ["It uses a calibrated loudspeaker", "Three microphones are measured in pairs, one emitting and one receiving; each pair gives a product of two sensitivities, and three products determine all three", "It weighs the diaphragm", "It compares against the BIPM's master microphone"], c: 1, why: "A condenser microphone is reciprocal: it works as a source with the same transduction constant. In a coupler (pressure) or an anechoic room (free field) the electrical transfer impedance of a pair gives M₁·M₂ times known acoustics. Three pairs, three unknowns." },
    { q: "Why should a pistonphone's cavity be large compared with the microphone's equivalent volume?", a: ["To make it louder", "So that the microphone's impedance, in parallel with the cavity compliance, barely changes the pressure: the level must not depend on which microphone is inserted", "To lower the frequency", "So that it fits larger microphones"], c: 1, why: "<span class='m'>p = (1/j\\omega C_A \\parallel Z_A)\\,U_i</span>. With <span class='m'>Z_A \\gg 1/\\omega C_A</span> the pressure is <span class='m'>\\gamma p_s \\Delta V / V</span>, independent of the microphone. The cavity must still be much smaller than the wavelength, and the p_s in the formula is why a barometric correction is needed." },
  ],
  "A": [
    { q: "Part 1, soft link: why does the coil velocity <b>dip</b> by 30 dB near 1.3 kHz?", a: ["The spider suspension resonates", "The outer cone on the soft link is a tuned absorber: its reaction force through C<sub>md</sub> cancels the drive force", "The coil inductance blocks the current", "Numerical error in LTspice"], c: 1, why: "A mass on a spring attached to a driven body resonates and pumps force back — a tuned-mass damper. The coil almost stops (anti-resonance, |Z_M| maximum of 334 Ns/m) while the cone still moves. Above that the link cannot transmit force and the light inner cone alone carries the treble: a mechanical crossover." },
    { q: "Part 1b: with a 1 A force source in the mobility analogy, the mechanical input impedance is…", a: ["<span class='m'>V(u_{vc})</span>", "<span class='m'>1/V(u_{vc})</span>", "<span class='m'>I(F)</span>", "<span class='m'>V(u_{vc}) \cdot I(F)</span>"], c: 1, why: "Mobility: velocity is a node voltage, force is a current. <span class='m'>Z_M = f/u = 1/V(u_{vc})</span> when the source is 1 A — exactly the waveform-arithmetic hint in the brief (Add Traces → 1/V(u_vc))." },
    { q: "Part 2: why does a pressure source and a volume-velocity source give peaks at <b>different</b> frequencies for the same silencer?", a: ["The two simulations used different element values", "A pressure source short-circuits the inlet, a volume-velocity source open-circuits it, so each excites the other set of natural frequencies (Z<sub>in</sub> minima vs. maxima)", "The volume-velocity source ignores the losses", "They give the same peaks; only the level differs"], c: 1, why: "The transfer is a property of the network; the source decides which boundary condition the inlet sees. p-source peaks = Z_in minima (77, 180, 356 Hz); U-source peaks = Z_in maxima (47, 176, 191 Hz, about +40 dB with an ideal source), where the p-source response has its dips. A real engine sits in between." },
    { q: "Part 2d: the effective lengths in the table already contain the end correction. When you add the radiation network to the last pipe you must…", a: ["Add the end correction a second time to be safe", "Shorten the pipe by 0.6133·a so the radiation mass M<sub>A1</sub> is not counted twice", "Remove the pipe entirely", "Double the pipe's resistance"], c: 1, why: "M_A1 = 0.6133ρ/(πa) is the same air the effective length already includes. Keep it once: either shorten the pipe (38.77 mm) or drop M_A1 from the network. Here the radiation load is ≥ 30× smaller than the pipe impedance anyway, so U_out changes by < 0.01 dB." },
    { q: "Part 3: what does the air load do to the dual-diaphragm speaker?", a: ["Nothing measurable", "Adds co-moving mass at low frequency (51 → 44 Hz) and damping around and above ka ≈ 1 (the absorber wall drops from 334 to 129 Ns/m)", "Raises every resonance", "Only changes the phase"], c: 1, why: "Below ka = 1 the radiation impedance is a mass: 0.5 g on the inner cone, 3.4 g on the outer. Above ka = 1 it is a resistance ρc·S² per side (4.9 and 17 Ns/m), which is both the radiated power and what damps the absorber. Both signs of change are the evidence that the coupling polarity is right." },
    { q: "Part 4: how do you know the back-EMF source has the correct sign?", a: ["The simulation runs without errors", "The 4.9 Hz velocity peak is small (≈ 0.65 m/s per V) and the current at resonance drops — the induced voltage opposes the drive; flipped, the high mode grows (negative damping)", "Z<sub>E</sub> is flat", "The coil velocity is zero everywhere"], c: 1, why: "Electrical damping (Bl)²/R_c = 4.5 Ns/m dominates the low mode. Without back-EMF the peak is ~30 m/s per V; with the wrong sign energy is fed in. Power check: v·i into the E source equals f·u out of the G source — the transducer is lossless." },
  ],
};
