/* Self-checks per lecture. c = index of the correct answer. */
"use strict";
window.QUIZZES = {
  "1": [
    { q: "In a plane wave of 1 Pa amplitude, how fast does the air itself move?", a: ["343 m/s — with the wave", "About 2.4 mm/s, back and forth", "It does not move at all; only pressure changes", "It depends on the frequency"], c: 1, why: "<span class='m'>U = P/\\rho c = 1/413</span> m/s. The pattern travels at c; the particles only oscillate about their rest position, independent of frequency (the displacement does depend on frequency, <span class='m'>\\Xi = U/j\\omega</span>)." },
    { q: "Why does the derivation of the wave equation use γ (adiabatic) rather than the isothermal gas law?", a: ["Because sound only exists in hot gases", "Because compressions in sound are far too fast for heat to flow, so pressure rises more than isothermally", "Because γ makes the algebra simpler", "It does not; γ is a unit conversion"], c: 1, why: "In one period there is no time for heat exchange between compressed and rarefied regions, so <span class='m'>p = -\\gamma p_0\\,\\Delta V/V</span> and <span class='m'>c^2 = \\gamma p_0/\\rho_0</span>. The isothermal value would give 290 m/s instead of 343." },
    { q: "Two equal coherent sources with a 180° lag cancel; with 179° the sum is…", a: ["Also zero — a degree does not matter", "About 1.7 % of one source (8.7 mPa for 0.5 Pa each)", "Half of one source", "Twice one source"], c: 1, why: "<span class='m'>|1 + e^{-j179^\\circ}| = 2|\\cos 89.5^\\circ| = 0.0175</span>. Cancellation is exact only for exact antiphase and equal amplitudes — the reason noise cancelling is hard above a few hundred hertz." },
    { q: "The temperature of a hall rises from 15 to 32 °C. The speed of sound…", a: ["rises by 32/15 ≈ 2.1×", "rises by √(305/288) ≈ 1.029×", "falls, because warm air is thinner", "is unchanged; c depends only on pressure"], c: 1, why: "<span class='m'>c = \\sqrt{\\gamma R_s T}</span> with T in kelvin. Density and pressure both change with temperature, but their ratio only through T — and c does not depend on the static pressure at all." },
  ],
  "2": [
    { q: "At a rigid wall a sound wave has…", a: ["a pressure node and a velocity antinode", "a pressure antinode and a velocity node", "nodes of both", "antinodes of both"], c: 1, why: "The air cannot move into the wall, so U = 0 there; the incident and reflected pressures add (R = +1) to 2P_i. The first pressure node is λ/4 in front of the wall." },
    { q: "Why does the reflected wave carry a minus sign in the velocity but not in the pressure?", a: ["A convention with no physical meaning", "Velocity is a vector: the reflected wave's motion points the other way; pressure is a scalar", "Because reflection inverts pressure", "Because the reflected wave loses energy"], c: 1, why: "<span class='m'>U_x = (P_i e^{-jkx} - P_r e^{jkx})/\\rho c</span>. Each travelling wave has <span class='m'>U = \\pm P/\\rho c</span> according to its direction; at a rigid wall the two velocities cancel while the two pressures add." },
    { q: "Sound goes from air into water (R = 0.9994). The pressure in the water is…", a: ["0.06 % of the incident pressure", "about half of it", "about twice the incident pressure, though only 0.1 % of the power gets in", "equal to it"], c: 2, why: "<span class='m'>T_p = 1 + R \\approx 2</span>: pressure is continuous and the incident and reflected waves add at the interface. Power is another matter: <span class='m'>\\tau = 4Z_1Z_2/(Z_1+Z_2)^2 = 0.11\\,\\%</span>." },
    { q: "Close to a small source (kr ≪ 1) the particle velocity is…", a: ["equal to P/ρc, as in a plane wave", "larger than P/ρc and roughly 90° out of phase with the pressure", "zero", "smaller than P/ρc"], c: 1, why: "<span class='m'>U_r = (P/\\rho c)(1 + 1/jkr)</span>: the near-field term dominates for small kr, giving a large quadrature (reactive) velocity that carries no net power. At 250 Hz and 10 cm it is 2.4× the plane-wave value and 65° behind." },
    { q: "A closed–open tube of length L has resonances at…", a: ["nc/2L, all harmonics", "(2n−1)c/4L, odd harmonics only", "nc/L", "c/L only"], c: 1, why: "The closed end is a velocity node, the open end a pressure node: a quarter wavelength (plus whole half wavelengths) must fit. That is why a closed organ pipe sounds an octave below an open one of the same length and has a hollow, odd-harmonic timbre." },
  ],
  "3": [
    { q: "Two independent machines each give 75 dB at a point. Together they give…", a: ["150 dB", "81 dB", "78 dB", "75 dB"], c: 2, why: "Uncorrelated sources add their mean-square pressures: <span class='m'>10\\log(2) = 3</span> dB more. Only coherent sources (same tone, fixed phase) can reach +6 dB or cancel." },
    { q: "L_eq of a source that is on at 85 dB half the time and a 70 dB background otherwise is closest to…", a: ["77.5 dB, the average of the two", "82 dB", "85 dB", "70 dB"], c: 1, why: "<span class='m'>L_{eq} = 10\\log\\overline{p^2/p_{ref}^2}</span>: average the squared pressure, not the decibels. Half the time at <span class='m'>10^{8.5}</span> plus <span class='m'>10^{7}</span> gives <span class='m'>10\\log(0.5\\cdot 3.16\\times10^8 + 10^7) \\approx 82.3</span> dB." },
    { q: "A signal with period 1.3 ms has harmonics at 769 Hz, 1538, 2308, 3077 … The 2 kHz octave band (1414–2828 Hz) contains…", a: ["one component", "two components → the band level is the component level + 3 dB", "three components", "none"], c: 1, why: "1538 and 2308 Hz fall inside; components at different frequencies are uncorrelated, so two equal ones give +10 log 2 = 3 dB. The 4 kHz band gets four (+6 dB)." },
    { q: "White noise analysed in 1/3-octave bands shows a level that…", a: ["is flat", "rises 1 dB per band", "falls 3 dB per band", "rises 3 dB per band"], c: 1, why: "White noise has constant power per hertz, and each 1/3-octave band is <span class='m'>2^{1/3}</span> wider than the previous: <span class='m'>10\\log 2^{1/3} = 1</span> dB. Pink noise (constant power per octave) is flat in constant-percentage bands, which is why it sounds balanced." },
    { q: "A 100 Hz tone measures 70 dB unweighted. A-weighted it reads about…", a: ["70 dB(A)", "51 dB(A)", "89 dB(A)", "66 dB(A)"], c: 1, why: "The A-weighting response at 100 Hz is −19.1 dB (table 1.3.2): the meter mimics the ear's low-level insensitivity to bass. C-weighting would take off only 0.3 dB." },
  ],
};
