"""Markdown the sync writes into the vault.

These notes are committed to git directly -- they are text, so they do not go
through drive-sync. The Home.md injection is deliberately conservative: it only
ever touches the region between its own markers.
"""

from __future__ import annotations

import re

VAULT_PREFIX = "Obsidian/"


def _wiki_link(vault_path: str, title: str) -> str:
    """An Obsidian wiki link, relative to the vault root rather than the repo root."""
    target = vault_path[len(VAULT_PREFIX):] if vault_path.startswith(VAULT_PREFIX) else vault_path
    return f"[[{target}|{title}]]"


# --- Home.md marker injection -------------------------------------------------


def inject_block(document: str, marker: str, body: str) -> str:
    """Replace the region between `marker` start/end comments, or append one.

    Content outside the markers is never modified. Running this twice with the
    same body is a no-op, so a sync that changes nothing leaves Home.md byte for
    byte identical and produces no commit.
    """
    start = f"<!-- {marker}:start -->"
    end = f"<!-- {marker}:end -->"
    block = f"{start}\n{body.rstrip()}\n{end}"

    pattern = re.compile(
        re.escape(start) + r".*?" + re.escape(end),
        re.DOTALL,
    )

    if pattern.search(document):
        return pattern.sub(lambda _: block, document, count=1)

    separator = "" if document.endswith("\n\n") or not document else "\n"
    return f"{document}{separator}\n{block}\n"


# --- INDEX.md -----------------------------------------------------------------


def render_index(course_name: str, entries) -> str:
    """The Brightspace module tree, linking to wherever each file was filed.

    This is the ground-truth view of the course. Module order is preserved
    exactly as Brightspace returned it, since that is the order a lecturer chose.
    """
    lines = [
        f"# {course_name} — Learn contents",
        "",
        "*Generated by learn-sync. Mirrors the DTU Learn module tree; each entry",
        "links to where the file actually lives in the vault.*",
        "",
    ]

    seen: list[tuple[str, ...]] = []
    for module_path, title, vault_path in entries:
        for depth in range(1, len(module_path) + 1):
            prefix = module_path[:depth]
            if prefix not in seen:
                seen.append(prefix)
                # A blank line before the heading, none between items: Obsidian
                # renders a list with blank lines between entries as a loose list.
                if lines and lines[-1] != "":
                    lines.append("")
                lines.append(f"{'#' * (depth + 1)} {prefix[-1]}")
                lines.append("")
        lines.append(f"- {_wiki_link(vault_path, title)}")

    return "\n".join(lines).rstrip() + "\n"


# --- Announcements.md ---------------------------------------------------------

_HEADING = "# Announcements"


def render_announcements(existing: str, new) -> str:
    """Prepend new posts above existing ones, newest first. Never rewrites history."""
    ordered = sorted(new, key=lambda a: a.posted_at, reverse=True)
    rendered = "\n".join(
        f"## {a.posted_at:%Y-%m-%d} — {a.title}\n\n{a.body_markdown.strip()}\n"
        for a in ordered
    )

    if not existing.strip():
        return f"{_HEADING}\n\n{rendered}" if rendered else f"{_HEADING}\n"

    if not rendered:
        return existing

    if existing.lstrip().startswith(_HEADING):
        head, _, tail = existing.partition(_HEADING)
        tail = tail.lstrip("\n")
        return f"{head}{_HEADING}\n\n{rendered}\n{tail}"

    return f"{_HEADING}\n\n{rendered}\n{existing}"


# --- Deadlines ----------------------------------------------------------------


def render_deadlines(events) -> str:
    """A table of upcoming deadlines, soonest first, for the Home.md dashboard."""
    if not events:
        return "*No deadlines known from DTU Learn.*"

    lines = [
        "| Date | Course | What |",
        "|---|---|---|",
    ]
    for event in sorted(events, key=lambda e: e.starts_at):
        lines.append(f"| {event.starts_at:%Y-%m-%d} | {event.course_code} | {event.title} |")

    return "\n".join(lines)
